// flow-typed signature: b5d8c1a55f592fa39fdc5fe61364c868
// flow-typed version: <<STUB>>/capitalrx-logos_vfile:../capitalrx-logos/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'capitalrx-logos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'capitalrx-logos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'capitalrx-logos/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'capitalrx-logos/lib/index.js' {
  declare module.exports: $Exports<'capitalrx-logos/lib/index'>;
}
