// flow-typed signature: 5a994b30adda3c74250fcf4e2a928167
// flow-typed version: <<STUB>>/capitalrx-progress_vfile:../capitalrx-progress/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'capitalrx-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'capitalrx-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'capitalrx-progress/lib/actions/index' {
  declare module.exports: any;
}

declare module 'capitalrx-progress/lib/components/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'capitalrx-progress/lib/constants/index' {
  declare module.exports: any;
}

declare module 'capitalrx-progress/lib/index' {
  declare module.exports: any;
}

declare module 'capitalrx-progress/lib/reducers/progress/index' {
  declare module.exports: any;
}

declare module 'capitalrx-progress/lib/utils/progress/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'capitalrx-progress/lib/actions/index.js' {
  declare module.exports: $Exports<'capitalrx-progress/lib/actions/index'>;
}
declare module 'capitalrx-progress/lib/components/ProgressBar/index.js' {
  declare module.exports: $Exports<'capitalrx-progress/lib/components/ProgressBar/index'>;
}
declare module 'capitalrx-progress/lib/constants/index.js' {
  declare module.exports: $Exports<'capitalrx-progress/lib/constants/index'>;
}
declare module 'capitalrx-progress/lib/index.js' {
  declare module.exports: $Exports<'capitalrx-progress/lib/index'>;
}
declare module 'capitalrx-progress/lib/reducers/progress/index.js' {
  declare module.exports: $Exports<'capitalrx-progress/lib/reducers/progress/index'>;
}
declare module 'capitalrx-progress/lib/utils/progress/index.js' {
  declare module.exports: $Exports<'capitalrx-progress/lib/utils/progress/index'>;
}
