// flow-typed signature: 88e83559db7a69e9ad4ebe2f8aa8d057
// flow-typed version: <<STUB>>/jwt-js_v^0.5.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwt-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwt-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jwt-js/lib/crypto-clients' {
  declare module.exports: any;
}

declare module 'jwt-js/lib/decode' {
  declare module.exports: any;
}

declare module 'jwt-js/lib/errors' {
  declare module.exports: any;
}

declare module 'jwt-js/lib/signer' {
  declare module.exports: any;
}

declare module 'jwt-js/lib/signing-algorithms/secp256k1' {
  declare module.exports: any;
}

declare module 'jwt-js/lib/utils' {
  declare module.exports: any;
}

declare module 'jwt-js/lib/verifier' {
  declare module.exports: any;
}

declare module 'jwt-js/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jwt-js/index' {
  declare module.exports: $Exports<'jwt-js'>;
}
declare module 'jwt-js/index.js' {
  declare module.exports: $Exports<'jwt-js'>;
}
declare module 'jwt-js/lib/crypto-clients.js' {
  declare module.exports: $Exports<'jwt-js/lib/crypto-clients'>;
}
declare module 'jwt-js/lib/decode.js' {
  declare module.exports: $Exports<'jwt-js/lib/decode'>;
}
declare module 'jwt-js/lib/errors.js' {
  declare module.exports: $Exports<'jwt-js/lib/errors'>;
}
declare module 'jwt-js/lib/signer.js' {
  declare module.exports: $Exports<'jwt-js/lib/signer'>;
}
declare module 'jwt-js/lib/signing-algorithms/secp256k1.js' {
  declare module.exports: $Exports<'jwt-js/lib/signing-algorithms/secp256k1'>;
}
declare module 'jwt-js/lib/utils.js' {
  declare module.exports: $Exports<'jwt-js/lib/utils'>;
}
declare module 'jwt-js/lib/verifier.js' {
  declare module.exports: $Exports<'jwt-js/lib/verifier'>;
}
declare module 'jwt-js/test.js' {
  declare module.exports: $Exports<'jwt-js/test'>;
}
