// @flow

export const ActionTypes = {
  AUTHNZ_SHOW_EMAIL_ENTRY: "AUTHNZ_SHOW_EMAIL_ENTRY",
  AUTHNZ_SHOW_PASSWORD_ENTRY: "AUTHNZ_SHOW_PASSWORD_ENTRY",
  AUTHNZ_DISABLE_LOGIN_BUTTON: "AUTHNZ_DISABLE_LOGIN_BUTTON",
  AUTHNZ_SHOW_TOTP_ENTRY: "AUTHNZ_SHOW_TOTP_ENTRY",
  AUTHNZ_SHOW_TOTP_SETUP: "AUTHNZ_SHOW_TOTP_SETUP",
  AUTHNZ_RECEIVE_TOTP_URI: "AUTHNZ_RECEIVE_TOTP_URI",
  AUTHNZ_RECEIVED_TOKEN: "AUTHNZ_RECEIVED_TOKEN",
  AUTHNZ_RESET: "AUTHNZ_RESET",
  AUTHNZ_DID_LOG_OUT: "AUTHNZ_DID_LOG_OUT",
};

export const AuthnzStateTypes = {
  SHOW_EMAIL_ENTRY: "SHOW_EMAIL_ENTRY",
  SHOW_PASSWORD_ENTRY: "SHOW_PASSWORD_ENTRY",
  SHOW_TOTP_ENTRY: "SHOW_TOTP_ENTRY",
  SHOW_TOTP_SETUP: "SHOW_TOTP_SETUP",
};
